CREATE TABLE orders (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      BIGINT         NOT NULL,
    status           VARCHAR(20)    NOT NULL,
    total_amount     NUMERIC(12, 2) NOT NULL,
    shipping_address VARCHAR(500)   NOT NULL,
    created_at       TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES users (id)
);

CREATE TABLE order_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT         NOT NULL,
    product_id   BIGINT         NOT NULL,
    store_id     BIGINT         NOT NULL,
    product_name VARCHAR(200)   NOT NULL,
    unit_price   NUMERIC(12, 2) NOT NULL,
    quantity     INTEGER        NOT NULL,
    CONSTRAINT chk_order_items_qty CHECK (quantity > 0),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_order_items_store FOREIGN KEY (store_id) REFERENCES stores (id)
);

CREATE TABLE payments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          BIGINT         NOT NULL,
    reference         VARCHAR(64)    NOT NULL,
    amount            NUMERIC(12, 2) NOT NULL,
    status            VARCHAR(20)    NOT NULL,
    authorization_url VARCHAR(500),
    access_code       VARCHAR(100),
    paid_at           TIMESTAMP,
    created_at        TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payments_reference UNIQUE (reference),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id)
);

CREATE INDEX idx_orders_customer ON orders (customer_id);
CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_order_items_order ON order_items (order_id);
CREATE INDEX idx_order_items_store ON order_items (store_id);
CREATE INDEX idx_order_items_product ON order_items (product_id);
CREATE INDEX idx_payments_order ON payments (order_id);
